[package]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@origin-labs.com>"]
copyright = "OCamlPro SAS & Origin Labs SAS"
description = "The drom OCaml project"
edition = "4.10.0"
github-organization = "ocamlpro"
kind = "both"
name = "drom"
synopsis = "The drom project"
version = "0.1.0"

# keys that you could also define:
# license = "...license..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# documentation = "...documentation..."
# homepage = "...homepage..."

[dependencies]
opam-file-format = "2.0.0"
ez-cmdliner = "0.1.0"
ez-file = "0.1.0"
ez-config = "0.1.0"
toml = "5.0.0"

[tools]
dune = "2.6.0"
