[project]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@origin-labs.com>"]
copyright = "OCamlPro SAS & Origin Labs SAS"
edition = "4.10.0"
github-organization = "ocamlpro"
license = "LGPL2"
min-edition = "4.03.0"
mode = "binary"
name = "drom"
synopsis = "The drom tool is a wrapper over opam/dune in an attempt to provide a cargo-like user experience"
version = "0.1.0"
windows-ci = false

# keys that you could also define:
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]
description = """
The drom tool is a wrapper over opam/dune in an attempt to provide a cargo-like
user experience. It can be used to create full OCaml projects with
sphinx and odoc documentation. It has specific knowledge of Github and
will generate files for Github Actions CI and Github pages.
"""

[drom]
skip = "src/main.ml sphinx/index.rst CHANGES.md"

[dependencies]

[tools]

[profile.dev]
ocaml-flags = "-w -a"
[profile.release]
ocaml-flags = "-O3"
[project]
pack-modules = true
skip-dirs = [ "test" ]


[[package]]
dir = "main"
driver-only = "Drom_lib.Main.main"
kind = "program"
name = "drom"
[package.dependencies]
drom_lib = "version"

[[package]]
dir = "src"
gen-version = "version.ml"
kind = "library"
name = "drom_lib"
pack-modules = true
[package.dependencies]
ez_cmdliner = "0.1.0"
ez_config = "0.1.0"
ez_file = "0.1.0"
opam-file-format = "2.0.0"
toml = "5.0.0"

